// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjnynbmfbbhwuibafsgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbnluYm1mYmJod3VpYmFmc2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzA3NTEsImV4cCI6MjA2OTc0Njc1MX0.ApZxriXJcXeLx8opTmGnYh9dvZw_xv4VPXWmlrDkgYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});